import type { Experience, Fleet, Package, SiteSetting, Stay, Story } from '@/payload-types'

/**
 * Built-in sample content, used when no Payload backend is configured
 * (i.e. PAYLOAD_SECRET is unset — e.g. a zero-config Vercel deploy). This keeps
 * the public site fully live with no database. Once a production database +
 * PAYLOAD_SECRET are set, queries read from Payload/admin instead of this.
 *
 * Package photos live at `public/packages/<slug>.jpg` — to use your own photo,
 * just replace that file (same name). See public/packages/README.md.
 */

const items = (arr: string[]) => arr.map((item, i) => ({ id: String(i + 1), item }))
const img = (slug: string, alt: string) => ({ url: `/packages/${slug}.jpg`, alt })
const carImg = (file: string, alt: string) => ({ url: `/fleet/${file}.jpg`, alt })
const expImg = (file: string, alt: string) => ({ url: `/experiences/${file}.jpg`, alt })
const stayImg = (file: string, alt: string) => ({ url: `/stays/${file}.jpg`, alt })
const carFeatures = items(['AC', 'Music system', 'Experienced driver'])

export const siteSettings = {
  brandTagline: 'Har Safar, Yaadgaar Safar',
  heroHeadline: 'Taxi se Hotel tak, Khana se Heritage tak',
  heroSubline: 'Sab Kuch Best, Sirf Aapke Liye!',
  phone: '+91 92044 19881',
  whatsappNumber: '919204419881',
  email: null,
  instagram: '@kartikart.travels',
  address: 'Deoghar, Jharkhand 814112',
  mapEmbedUrl: null,
  whatsappDefaultMessage: 'Hi Kartikart! I would like to plan a trip. Please help me with a quote.',
} as unknown as SiteSetting

export const packages = [
  {
    id: 1,
    title: '2-Day Baidyanath Darshan & Local Sightseeing',
    slug: 'baba-baidyanath-darshan',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'couples', 'solo'],
    durationDays: 2,
    durationNights: 1,
    priceFrom: 4500,
    compareAtPrice: 5000,
    priceNote: 'per cab · Dzire (Ertiga ₹5,600 · Innova ₹7,600)',
    shortPitch:
      'Airport pickup, full Baba Baidyanath Jyotirlinga darshan and the complete Deoghar circuit over two unhurried days — our cab, start to finish.',
    heroImage: img('baba-baidyanath-darshan', 'Baba Baidyanath Dham, Deoghar'),
    highlights: items([
      'Baidyanath Jyotirlinga darshan',
      'Basukinath Dham',
      'Trikut Parwat ropeway',
      'Tapovan Caves & Naulakha Temple',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Airport pickup & Baidyanath darshan', details: 'Pickup from Deoghar Airport, Baba Baidyanath Jyotirlinga darshan and evening at leisure.' },
      { id: '2', day: 2, title: 'Local sightseeing & drop', details: 'Basukinath Temple, Trikut Parwat, Tapovan Caves and Naulakha Temple, then drop to Deoghar Airport.' },
    ],
    inclusions: items(['AC cab (2 days)', 'Driver & fuel', 'Airport pickup & drop', 'Toll & parking (Ertiga / Innova)']),
    exclusions: items(['Hotel & meals', 'Pooja items', 'Ropeway tickets']),
  },
  {
    id: 2,
    title: 'Same-Day Deoghar Local Darshan',
    slug: 'deoghar-bashukinath',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 2500,
    priceNote: 'per cab (Dzire) · + parking',
    shortPitch:
      'The whole Deoghar circuit in one day by cab — Baidyanath, Basukinath, Trikut Parwat, Tapovan Caves and Naulakha Temple.',
    heroImage: img('deoghar-bashukinath', 'Basukinath Dham temple'),
    highlights: items([
      'Baba Baidyanath darshan',
      'Basukinath Dham',
      'Trikut Parwat',
      'Tapovan Caves & Naulakha Temple',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Full-day darshan circuit', details: 'Baidyanath Temple, Basukinath Temple, Trikut Parwat, Tapovan Caves and Naulakha Temple — one cab, one smooth day.' },
    ],
    inclusions: items(['AC cab (8 hrs / 80 km)', 'Driver & fuel', 'All five sightseeing points']),
    exclusions: items(['Parking charges', 'Pooja items', 'Meals']),
  },
  {
    id: 3,
    title: 'Deoghar – Sultanganj – Bashukinath Kanwar Yatra',
    slug: 'deoghar-sultanganj-bashukinath',
    status: 'published',
    featured: false,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'groups'],
    durationDays: 2,
    durationNights: 1,
    priceFrom: 6999,
    priceNote: 'per cab (2 days)',
    shortPitch:
      'The classic Kanwar route — holy Ganga jal from Sultanganj to Baba Baidyanath, then Basukinath Dham.',
    heroImage: img('deoghar-sultanganj-bashukinath', 'Sultanganj Ganga ghat & Ajgaibinath'),
    highlights: items([
      'Ganga jal from Sultanganj',
      'Ajgaibinath temple',
      'Baidyanath Dham darshan',
      'Basukinath Dham darshan',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Sultanganj', details: 'Drive to Sultanganj, Ganga snan & jal at Ajgaibinath, begin the kanwar route.' },
      { id: '2', day: 2, title: 'Baidyanath & Basukinath', details: 'Baba Baidyanath darshan and Basukinath Dham, then return.' },
    ],
    inclusions: items(['AC cab (2 days)', 'Driver & fuel', 'Toll & parking']),
    exclusions: items(['Hotel & meals', 'Pooja items']),
  },
  {
    id: 4,
    title: 'Deoghar · Basukinath · Trikut Pahad',
    slug: 'deoghar-bashukinath-trikut',
    status: 'published',
    featured: false,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 2500,
    priceNote: 'per cab (Dzire) · + parking',
    shortPitch:
      'Darshan with a little adventure — Baidyanath and Basukinath plus the Trikut Parwat ropeway, all in a day.',
    heroImage: img('deoghar-bashukinath-trikut', 'Trikut Pahad hills'),
    highlights: items([
      'Baidyanath & Basukinath darshan',
      'Trikut Parwat ropeway',
      'Tapovan Caves',
      'Hilltop views',
    ]),
    inclusions: items(['AC cab (8 hrs / 80 km)', 'Driver & fuel']),
    exclusions: items(['Ropeway tickets', 'Parking', 'Meals']),
  },
  {
    id: 5,
    title: 'Deoghar · Gaya · Bodh Gaya Yatra',
    slug: 'deoghar-gaya-bodhgaya',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'pan-india',
    suitedFor: ['families', 'groups', 'couples'],
    durationDays: 2,
    durationNights: 1,
    priceFrom: 9999,
    priceNote: 'per cab · Ertiga (2 days)',
    shortPitch:
      'Pind-daan and darshan at Gaya’s Vishnupad, then the great Mahabodhi Temple at Bodh Gaya — two guided days by cab.',
    heroImage: img('deoghar-gaya-bodhgaya', 'Mahabodhi Temple, Bodh Gaya'),
    highlights: items([
      'Vishnupad Temple, Gaya',
      'Mahabodhi Temple, Bodh Gaya',
      'The sacred Bodhi Tree',
      'Two-day guided cab',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Deoghar → Gaya', details: 'Drive to Gaya, Vishnupad Temple and the ghats, overnight.' },
      { id: '2', day: 2, title: 'Bodh Gaya & return', details: 'Mahabodhi Temple, Bodhi Tree and the monasteries at Bodh Gaya, then return.' },
    ],
    inclusions: items(['AC Ertiga (2 days)', 'Driver & fuel', 'Toll, parking & driver allowance']),
    exclusions: items(['Hotel & meals', 'Pooja / pind-daan charges']),
  },
  {
    id: 6,
    title: 'Deoghar → Tarapith (via Basukinath)',
    slug: 'deoghar-tarapith',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'pan-india',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 4999,
    priceNote: 'per cab · Ertiga (day trip)',
    shortPitch:
      'A day trip to the Tarapith Shakti Peeth in Bengal, with a Basukinath Dham darshan along the way.',
    heroImage: img('deoghar-tarapith', 'Tarapith temple, West Bengal'),
    highlights: items([
      'Tarapith Maa Tara temple',
      'Basukinath Dham on the way',
      'Shakti Peeth darshan',
      'Same-day round trip',
    ]),
    inclusions: items(['AC Ertiga (day trip)', 'Driver & fuel', 'Toll & parking']),
    exclusions: items(['Meals', 'Pooja items']),
  },
  {
    id: 7,
    title: 'Deoghar to Gangtok Escape',
    slug: 'deoghar-gangtok',
    status: 'published',
    featured: true,
    category: 'adventure',
    region: 'pan-india',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 6,
    durationNights: 5,
    priceFrom: 21999,
    priceNote: 'per person',
    shortPitch:
      'From the Dham to the Himalayas — Gangtok’s monasteries, Tsomgo Lake and mountain air.',
    heroImage: img('deoghar-gangtok', 'Gangtok, Sikkim mountains'),
    highlights: items(['Gangtok city & MG Marg', 'Tsomgo Lake & Baba Mandir', 'Monasteries', 'Himalayan views']),
    itinerary: [
      { id: '1', day: 1, title: 'Journey', details: 'Deoghar to NJP / Bagdogra, transfer to Gangtok.' },
      { id: '2', day: 2, title: 'Gangtok local', details: 'Monasteries, viewpoints, MG Marg.' },
      { id: '3', day: 3, title: 'Tsomgo Lake', details: 'Tsomgo Lake and Baba Harbhajan Mandir.' },
      { id: '4', day: 4, title: 'Leisure', details: 'Cable car, local markets, optional excursions.' },
      { id: '5', day: 5, title: 'Return transfer', details: 'Back to NJP / Bagdogra.' },
      { id: '6', day: 6, title: 'Home', details: 'Return to Deoghar.' },
    ],
    inclusions: items(['Transfers', '5 nights stay', 'Daily breakfast', 'Sightseeing cab']),
    exclusions: items(['Flights/trains', 'Permits', 'Lunch & dinner']),
  },
  {
    id: 8,
    title: 'Deoghar to Darjeeling Hills',
    slug: 'deoghar-darjeeling',
    status: 'published',
    featured: false,
    category: 'adventure',
    region: 'pan-india',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 6,
    durationNights: 5,
    priceFrom: 20999,
    priceNote: 'per person',
    shortPitch:
      'Toy train, tea gardens and sunrise over Kanchenjunga — the Queen of the Hills from Deoghar.',
    heroImage: img('deoghar-darjeeling', 'Darjeeling tea hills & toy train'),
    highlights: items(['Tiger Hill sunrise', 'Darjeeling toy train', 'Tea gardens', 'Batasia Loop']),
    itinerary: [
      { id: '1', day: 1, title: 'Journey', details: 'Deoghar to NJP, transfer to Darjeeling.' },
      { id: '2', day: 2, title: 'Tiger Hill & town', details: 'Sunrise at Tiger Hill, Ghoom monastery, Batasia Loop.' },
      { id: '3', day: 3, title: 'Tea & toy train', details: 'Tea garden visit and the heritage toy train.' },
      { id: '4', day: 4, title: 'Leisure', details: 'Mall Road, ropeway, local markets.' },
      { id: '5', day: 5, title: 'Return transfer', details: 'Back to NJP.' },
      { id: '6', day: 6, title: 'Home', details: 'Return to Deoghar.' },
    ],
    inclusions: items(['Transfers', '5 nights stay', 'Daily breakfast', 'Sightseeing cab']),
    exclusions: items(['Flights/trains', 'Entry tickets', 'Lunch & dinner']),
  },
  {
    id: 9,
    title: 'Deoghar ⇄ Dhanbad Taxi',
    slug: 'deoghar-dhanbad-taxi',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 2999,
    priceNote: 'one-way, from',
    shortPitch: 'Comfortable one-way or round-trip cab between Deoghar and Dhanbad, on your schedule.',
    heroImage: img('deoghar-dhanbad-taxi', 'Deoghar to Dhanbad highway'),
    highlights: items(['One-way or round trip', 'AC sedan or SUV', 'Doorstep pickup']),
    inclusions: items(['Cab, driver & fuel', 'Tolls (round trip)']),
    exclusions: items(['One-way tolls & parking']),
  },
  {
    id: 10,
    title: 'Deoghar ⇄ Ranchi Taxi',
    slug: 'deoghar-ranchi-taxi',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 4499,
    priceNote: 'one-way, from',
    shortPitch:
      'Deoghar to Ranchi (or back) with a driver who knows the route — airport, station or doorstep.',
    heroImage: img('deoghar-ranchi-taxi', 'Deoghar to Ranchi road'),
    highlights: items(['Airport & station drops', 'AC sedan or SUV', 'Flexible timing']),
    inclusions: items(['Cab, driver & fuel', 'Tolls (round trip)']),
    exclusions: items(['One-way tolls & parking']),
  },
  {
    id: 11,
    title: 'Daily Car Rentals',
    slug: 'daily-rentals',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 1500,
    priceNote: 'per day + ₹12/km · or ₹2,500 (8 hrs/80 km)',
    shortPitch:
      'Hire a car by the day for local darshan, sightseeing or errands — flexible per-day, 8hr/80km or hourly rates.',
    heroImage: img('daily-rentals', 'Kartikart car for daily rental'),
    highlights: items([
      'Per-day rental from ₹1,500 + ₹12/km',
      '8 hrs / 80 km @ ₹2,500',
      'Dzire, Ertiga, Rumion or Innova',
    ]),
    inclusions: items(['Car, driver & fuel (per package)', 'Local sightseeing route']),
    exclusions: items(['Extra km / hours', 'Parking & toll']),
  },
  {
    id: 12,
    title: 'Marriage & Event Rentals',
    slug: 'marriage-event-rentals',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: null,
    priceNote: 'on request',
    shortPitch:
      'Decorated cars and a full fleet for baraat, weddings and events — booked around your muhurat.',
    heroImage: img('marriage-event-rentals', 'Decorated wedding car'),
    highlights: items(['Decorated cars', 'Fleet for guests & baraat', 'On-time, muhurat-friendly']),
    inclusions: items(['Car(s) & drivers', 'Basic decoration (on request)']),
    exclusions: items(['Premium décor', 'Outstation charges']),
  },
] as unknown as Package[]

// Car photos live at `public/fleet/<file>.jpg` — drop your own in with these names.
// The fleet page shows the photo when the file exists, else a placeholder icon.
export const fleet = [
  { id: 1, name: 'Toyota Glanza', type: 'sedan', seats: 4, luggage: '2 bags', rate: 2200, rateNote: '8 hrs / 80 km · budget', photo: carImg('glanza', 'Toyota Glanza') },
  { id: 2, name: 'Maruti Suzuki Dzire', type: 'sedan', seats: 4, luggage: '2 bags', rate: 2500, rateNote: '8 hrs / 80 km', photo: carImg('dzire', 'Maruti Suzuki Dzire') },
  { id: 3, name: 'Toyota Rumion', type: 'suv', seats: 7, luggage: '3 bags', rate: 2500, rateNote: '8 hrs / 80 km · +₹12/km', photo: carImg('rumion', 'Toyota Rumion') },
  { id: 4, name: 'Maruti Suzuki Ertiga', type: 'suv', seats: 7, luggage: '3 bags', rate: 2500, rateNote: '8 hrs / 80 km · outstation available', photo: carImg('ertiga', 'Maruti Suzuki Ertiga') },
  {
    id: 5,
    name: 'Toyota Innova Crysta',
    type: 'suv',
    seats: 7,
    luggage: '4 bags',
    rate: 3500,
    compareAtRate: 3700,
    rateNote: '8 hrs / 80 km · +₹15/km · outstation ₹20/km',
    photo: carImg('innova-crysta', 'Toyota Innova Crysta'),
  },
].map((c) => ({
  ...c,
  ownedByKartikart: true,
  status: 'published',
  features: carFeatures,
})) as unknown as Fleet[]

export const stays = [
  {
    id: 1,
    name: 'Hotel Kartik',
    ownership: 'owned',
    location: 'Tower Chowk, Deoghar',
    starRating: null,
    priceFrom: null,
    priceNote: 'per night',
    shortDesc:
      'Kartikart’s own hotel, right on Tower Chowk — a premium address just 300 m (a short walk) from Baba Baidyanath Mandir.',
    mapUrl: 'https://maps.app.goo.gl/gTHHuuYULt8wd3DYA',
    status: 'published',
    amenities: items(['300 m from Baba Mandir', 'AC rooms', 'Free WiFi', 'Room service']),
    photos: [{ id: '1', image: stayImg('hotel-kartik', 'Hotel Kartik, Tower Chowk, Deoghar') }],
  },
] as unknown as Stay[]

export const experiences = [
  {
    id: 1,
    title: 'Chamari Sah Mistaan Bhandar',
    kind: 'food',
    location: 'Deoghar',
    specialty: 'Peda · Rasgulla · Chhena sweets',
    blurb:
      'One of Deoghar’s oldest sweet shops — famous for melt-in-the-mouth peda and rasgullas, made the authentic way for generations.',
    mapUrl: 'https://maps.app.goo.gl/f37SuJou6swFMDec6',
    featured: true,
    status: 'published',
    photos: [{ id: '1', image: expImg('chamari-sah-mistaan', 'Peda & rasgulla at Chamari Sah Mistaan, Deoghar') }],
  },
  {
    id: 2,
    title: 'Kailash Bhojnalaya',
    kind: 'food',
    location: 'Deoghar',
    specialty: 'Veg thali · Home-style bhojan',
    blurb:
      'Deoghar’s go-to for honest, home-style vegetarian food — a hearty in-house thali that tastes like it was cooked at home.',
    featured: true,
    status: 'published',
    photos: [{ id: '1', image: expImg('kailash-bhojnalaya', 'Vegetarian thali at Kailash Bhojnalaya, Deoghar') }],
  },
  {
    id: 3,
    title: 'Baba Baidyanath Dham & Heritage Walk',
    kind: 'heritage',
    location: 'Deoghar',
    specialty: 'Jyotirlinga · Tapovan · Naulakha',
    blurb:
      'The living heart of Deoghar — Baba Baidyanath Jyotirlinga darshan, the Tapovan caves and Naulakha temple, with the stories behind them.',
    featured: false,
    status: 'published',
    photos: [{ id: '1', image: { url: '/packages/baba-baidyanath-darshan.jpg', alt: 'Baba Baidyanath Dham, Deoghar' } }],
  },
] as unknown as Experience[]

export const stories = [
  {
    id: 1,
    customerName: 'Ramesh & Family',
    tripLabel: 'Baba Baidyanath Darshan, Mar 2026',
    tripType: 'spiritual',
    quote:
      'From the taxi to the hotel to the prasad thali — everything was handled. Truly Yaadgaar Safar!',
    rating: 5,
    featured: true,
    status: 'published',
    photos: null,
    date: null,
  },
] as unknown as Story[]
