import type { Experience, Fleet, Package, SiteSetting, Stay, Story } from '@/payload-types'

/**
 * Built-in sample content, used when no Payload backend is configured
 * (i.e. PAYLOAD_SECRET is unset — e.g. a zero-config Vercel deploy). This keeps
 * the public site fully live with no database. Once a production database +
 * PAYLOAD_SECRET are set, queries read from Payload/admin instead of this.
 *
 * Package photos live at `public/packages/<slug>.jpg` — to use your own photo,
 * just replace that file (same name). See public/packages/README.md.
 */

const items = (arr: string[]) => arr.map((item, i) => ({ id: String(i + 1), item }))
const img = (slug: string, alt: string) => ({ url: `/packages/${slug}.jpg`, alt })
const carFeatures = items(['AC', 'Music system', 'Experienced driver'])
const stayAmenities = items(['Free WiFi', 'Restaurant', 'Near Baba Mandir'])

export const siteSettings = {
  brandTagline: 'Har Safar, Yaadgaar Safar',
  heroHeadline: 'Taxi se Hotel tak, Khana se Heritage tak',
  heroSubline: 'Sab Kuch Best, Sirf Aapke Liye!',
  phone: '+91 9304781234',
  whatsappNumber: '916201234567',
  email: null,
  instagram: '@kartikart.travels',
  address: 'Deoghar, Jharkhand 814112',
  mapEmbedUrl: null,
  whatsappDefaultMessage: 'Hi Kartikart! I would like to plan a trip. Please help me with a quote.',
} as unknown as SiteSetting

export const packages = [
  {
    id: 1,
    title: 'Baba Baidyanath Jyotirlinga Darshan',
    slug: 'baba-baidyanath-darshan',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'solo'],
    durationDays: 3,
    durationNights: 2,
    priceFrom: 5999,
    priceNote: 'per person',
    shortPitch:
      'Darshan of one of the 12 Jyotirlingas, with taxi, stay and prasad-thali food handled end to end.',
    heroImage: img('baba-baidyanath-darshan', 'Baba Baidyanath Dham, Deoghar'),
    highlights: items(['Baidyanath Dham darshan', 'Tapovan & Nandan Pahar', 'Local prasad thali']),
    itinerary: [
      { id: '1', day: 1, title: 'Arrival & Mandir darshan', details: 'Pickup, hotel check-in, evening aarti.' },
      { id: '2', day: 2, title: 'Local heritage & food', details: 'Tapovan, Naulakha Mandir, heritage food trail.' },
      { id: '3', day: 3, title: 'Departure', details: 'Breakfast and drop.' },
    ],
    inclusions: items(['AC taxi', '2 nights stay', 'Daily breakfast']),
    exclusions: items(['Personal expenses', 'Pooja items']),
  },
  {
    id: 2,
    title: 'Deoghar – Bashukinath Darshan',
    slug: 'deoghar-bashukinath',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 3499,
    priceNote: 'per cab (day trip)',
    shortPitch:
      'Same-day darshan of Baba Baidyanath and Baba Basukinath — our cab, one smooth round trip.',
    heroImage: img('deoghar-bashukinath', 'Basukinath Dham temple'),
    highlights: items(['Baidyanath Dham darshan', 'Basukinath Dham darshan', 'AC cab, round trip']),
    inclusions: items(['AC taxi (Deoghar–Bashukinath–Deoghar)', 'Driver & fuel', 'Parking']),
    exclusions: items(['Pooja items', 'Meals']),
  },
  {
    id: 3,
    title: 'Deoghar – Sultanganj – Bashukinath Yatra',
    slug: 'deoghar-sultanganj-bashukinath',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'groups'],
    durationDays: 3,
    durationNights: 2,
    priceFrom: 8999,
    priceNote: 'per person',
    shortPitch:
      'The classic Kanwar route — holy Ganga jal from Sultanganj to Baba Baidyanath, then Basukinath.',
    heroImage: img('deoghar-sultanganj-bashukinath', 'Sultanganj Ganga ghat'),
    highlights: items([
      'Ganga jal from Sultanganj',
      'Baidyanath Dham darshan',
      'Basukinath Dham darshan',
      'Guided kanwar route',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Sultanganj', details: 'Drive to Sultanganj, Ganga snan & jal, Ajgaibinath temple.' },
      { id: '2', day: 2, title: 'Baidyanath Dham', details: 'Deoghar darshan, aarti, local heritage.' },
      { id: '3', day: 3, title: 'Basukinath & return', details: 'Basukinath darshan and drop.' },
    ],
    inclusions: items(['AC taxi', '2 nights stay', 'Daily breakfast']),
    exclusions: items(['Personal expenses', 'Pooja items']),
  },
  {
    id: 4,
    title: 'Deoghar – Bashukinath – Trikut Pahad',
    slug: 'deoghar-bashukinath-trikut',
    status: 'published',
    featured: true,
    category: 'spiritual',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 2,
    durationNights: 1,
    priceFrom: 4499,
    priceNote: 'per cab',
    shortPitch:
      'Darshan plus a little adventure — Baidyanath, Basukinath, and the Trikut Pahad ropeway.',
    heroImage: img('deoghar-bashukinath-trikut', 'Trikut Pahad ropeway hills'),
    highlights: items([
      'Baidyanath & Basukinath darshan',
      'Trikut Pahad ropeway',
      'Trikutachal Mahadeva',
      'Hilltop views',
    ]),
    itinerary: [
      { id: '1', day: 1, title: 'Darshan', details: 'Baidyanath and Basukinath darshan, overnight in Deoghar.' },
      { id: '2', day: 2, title: 'Trikut Pahad', details: 'Ropeway, hilltop temple, return drop.' },
    ],
    inclusions: items(['AC taxi', '1 night stay', 'Ropeway assistance']),
    exclusions: items(['Ropeway tickets', 'Meals']),
  },
  {
    id: 5,
    title: 'Deoghar to Gangtok Escape',
    slug: 'deoghar-gangtok',
    status: 'published',
    featured: true,
    category: 'adventure',
    region: 'pan-india',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 6,
    durationNights: 5,
    priceFrom: 21999,
    priceNote: 'per person',
    shortPitch:
      'From the Dham to the Himalayas — Gangtok’s monasteries, Tsomgo Lake and mountain air.',
    heroImage: img('deoghar-gangtok', 'Gangtok, Sikkim mountains'),
    highlights: items(['Gangtok city & MG Marg', 'Tsomgo Lake & Baba Mandir', 'Monasteries', 'Himalayan views']),
    itinerary: [
      { id: '1', day: 1, title: 'Journey', details: 'Deoghar to NJP / Bagdogra, transfer to Gangtok.' },
      { id: '2', day: 2, title: 'Gangtok local', details: 'Monasteries, viewpoints, MG Marg.' },
      { id: '3', day: 3, title: 'Tsomgo Lake', details: 'Tsomgo Lake and Baba Harbhajan Mandir.' },
      { id: '4', day: 4, title: 'Leisure', details: 'Cable car, local markets, optional excursions.' },
      { id: '5', day: 5, title: 'Return transfer', details: 'Back to NJP / Bagdogra.' },
      { id: '6', day: 6, title: 'Home', details: 'Return to Deoghar.' },
    ],
    inclusions: items(['Transfers', '5 nights stay', 'Daily breakfast', 'Sightseeing cab']),
    exclusions: items(['Flights/trains', 'Permits', 'Lunch & dinner']),
  },
  {
    id: 6,
    title: 'Deoghar to Darjeeling Hills',
    slug: 'deoghar-darjeeling',
    status: 'published',
    featured: false,
    category: 'adventure',
    region: 'pan-india',
    suitedFor: ['families', 'couples', 'groups'],
    durationDays: 6,
    durationNights: 5,
    priceFrom: 20999,
    priceNote: 'per person',
    shortPitch:
      'Toy train, tea gardens and sunrise over Kanchenjunga — the Queen of the Hills from Deoghar.',
    heroImage: img('deoghar-darjeeling', 'Darjeeling tea hills & toy train'),
    highlights: items(['Tiger Hill sunrise', 'Darjeeling toy train', 'Tea gardens', 'Batasia Loop']),
    itinerary: [
      { id: '1', day: 1, title: 'Journey', details: 'Deoghar to NJP, transfer to Darjeeling.' },
      { id: '2', day: 2, title: 'Tiger Hill & town', details: 'Sunrise at Tiger Hill, Ghoom monastery, Batasia Loop.' },
      { id: '3', day: 3, title: 'Tea & toy train', details: 'Tea garden visit and the heritage toy train.' },
      { id: '4', day: 4, title: 'Leisure', details: 'Mall Road, ropeway, local markets.' },
      { id: '5', day: 5, title: 'Return transfer', details: 'Back to NJP.' },
      { id: '6', day: 6, title: 'Home', details: 'Return to Deoghar.' },
    ],
    inclusions: items(['Transfers', '5 nights stay', 'Daily breakfast', 'Sightseeing cab']),
    exclusions: items(['Flights/trains', 'Entry tickets', 'Lunch & dinner']),
  },
  {
    id: 7,
    title: 'Deoghar ⇄ Dhanbad Taxi',
    slug: 'deoghar-dhanbad-taxi',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 2999,
    priceNote: 'one-way, from',
    shortPitch: 'Comfortable one-way or round-trip cab between Deoghar and Dhanbad, on your schedule.',
    heroImage: img('deoghar-dhanbad-taxi', 'Deoghar to Dhanbad highway'),
    highlights: items(['One-way or round trip', 'AC sedan or SUV', 'Doorstep pickup']),
    inclusions: items(['Cab, driver & fuel', 'Tolls (round trip)']),
    exclusions: items(['One-way tolls & parking']),
  },
  {
    id: 8,
    title: 'Deoghar ⇄ Ranchi Taxi',
    slug: 'deoghar-ranchi-taxi',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 4499,
    priceNote: 'one-way, from',
    shortPitch:
      'Deoghar to Ranchi (or back) with a driver who knows the route — airport, station or doorstep.',
    heroImage: img('deoghar-ranchi-taxi', 'Deoghar to Ranchi road'),
    highlights: items(['Airport & station drops', 'AC sedan or SUV', 'Flexible timing']),
    inclusions: items(['Cab, driver & fuel', 'Tolls (round trip)']),
    exclusions: items(['One-way tolls & parking']),
  },
  {
    id: 9,
    title: 'Daily Car Rentals',
    slug: 'daily-rentals',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'couples', 'groups', 'solo'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: 1999,
    priceNote: 'per day, from',
    shortPitch:
      'Hire a car by the day for local darshan, sightseeing or errands — hourly and daily packages.',
    heroImage: img('daily-rentals', 'Kartikart car for daily rental'),
    highlights: items(['Local sightseeing', 'Hourly / 8hr-80km / daily', 'Sedan, SUV or Tempo']),
    inclusions: items(['Car, driver & fuel (per package)', 'Local darshan route']),
    exclusions: items(['Extra km/hours', 'Parking']),
  },
  {
    id: 10,
    title: 'Marriage & Event Rentals',
    slug: 'marriage-event-rentals',
    status: 'published',
    featured: false,
    category: 'rental',
    region: 'deoghar',
    suitedFor: ['families', 'groups'],
    durationDays: 1,
    durationNights: 0,
    priceFrom: null,
    priceNote: 'on request',
    shortPitch:
      'Decorated cars and a full fleet for baraat, weddings and events — booked around your muhurat.',
    heroImage: img('marriage-event-rentals', 'Decorated wedding car'),
    highlights: items(['Decorated cars', 'Fleet for guests & baraat', 'On-time, muhurat-friendly']),
    inclusions: items(['Car(s) & drivers', 'Basic decoration (on request)']),
    exclusions: items(['Premium décor', 'Outstation charges']),
  },
] as unknown as Package[]

export const fleet = [
  { id: 1, name: 'Toyota Innova Crysta', type: 'suv', seats: 7 },
  { id: 2, name: 'Maruti Ertiga', type: 'suv', seats: 7 },
  { id: 3, name: 'Toyota Etios', type: 'sedan', seats: 4 },
  { id: 4, name: 'Maruti Dzire', type: 'sedan', seats: 4 },
  { id: 5, name: 'Force Tempo Traveller', type: 'tempo', seats: 12 },
].map((c) => ({
  ...c,
  ownedByKartikart: true,
  status: 'published',
  rateNote: 'on request',
  features: carFeatures,
  photo: null,
})) as unknown as Fleet[]

export const stays = [
  { id: 1, name: 'Kartikart Residency, Deoghar', ownership: 'owned', starRating: 3, priceFrom: 1999 },
  { id: 2, name: 'Kartikart Grand, Deoghar', ownership: 'owned', starRating: 4, priceFrom: 3499 },
  { id: 3, name: 'Shri Baidyanath Guest House (Partner)', ownership: 'partner', starRating: 3, priceFrom: 1499 },
].map((s) => ({
  ...s,
  location: 'Deoghar',
  priceNote: 'per night',
  status: 'published',
  amenities: stayAmenities,
  photos: null,
})) as unknown as Stay[]

export const experiences = [
  {
    id: 1,
    title: 'Deoghar Peda & Prasad Thali Trail',
    kind: 'food',
    location: 'Deoghar',
    partnerEatery: 'Local partner eateries',
    featured: true,
    status: 'published',
    photos: null,
  },
] as unknown as Experience[]

export const stories = [
  {
    id: 1,
    customerName: 'Ramesh & Family',
    tripLabel: 'Baba Baidyanath Darshan, Mar 2026',
    tripType: 'spiritual',
    quote:
      'From the taxi to the hotel to the prasad thali — everything was handled. Truly Yaadgaar Safar!',
    rating: 5,
    featured: true,
    status: 'published',
    photos: null,
    date: null,
  },
] as unknown as Story[]
