/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    packages: Package;
    fleet: Fleet;
    stays: Stay;
    experiences: Experience;
    stories: Story;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    packages: PackagesSelect<false> | PackagesSelect<true>;
    fleet: FleetSelect<false> | FleetSelect<true>;
    stays: StaysSelect<false> | StaysSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  featured?: boolean | null;
  category: 'spiritual' | 'adventure' | 'wildlife' | 'beach' | 'cultural' | 'rental';
  suitedFor?: ('families' | 'couples' | 'groups' | 'solo')[] | null;
  region: 'deoghar' | 'pan-india';
  durationDays?: number | null;
  durationNights?: number | null;
  /**
   * Starting price in ₹
   */
  priceFrom?: number | null;
  /**
   * Original price, shown struck through (optional — for a discount)
   */
  compareAtPrice?: number | null;
  /**
   * e.g. "per cab" or "per person"
   */
  priceNote?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  shortPitch?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        day?: number | null;
        title?: string | null;
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet".
 */
export interface Fleet {
  id: number;
  /**
   * e.g. Toyota Innova Crysta
   */
  name: string;
  type: 'suv' | 'sedan' | 'tempo' | 'other';
  seats?: number | null;
  /**
   * e.g. 3 bags
   */
  luggage?: string | null;
  features?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  photo?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Numeric rate in ₹
   */
  rate?: number | null;
  /**
   * Original rate, shown struck through (optional)
   */
  compareAtRate?: number | null;
  /**
   * e.g. "8 hrs / 80 km" or "on request"
   */
  rateNote?: string | null;
  ownedByKartikart?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays".
 */
export interface Stay {
  id: number;
  name: string;
  ownership: 'owned' | 'partner';
  location?: string | null;
  starRating?: number | null;
  amenities?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  photos?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  shortDesc?: string | null;
  /**
   * Google Maps link (optional — shows a "View on map" link)
   */
  mapUrl?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Starting price in ₹
   */
  priceFrom?: number | null;
  /**
   * e.g. "per night"
   */
  priceNote?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  kind: 'food' | 'heritage' | 'cultural';
  location?: string | null;
  /**
   * e.g. "Peda · Rasgulla · Sweets"
   */
  specialty?: string | null;
  /**
   * One or two lines shown on the card
   */
  blurb?: string | null;
  /**
   * Google Maps link (optional — shows a "View on map" link)
   */
  mapUrl?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional partner eatery / vendor name
   */
  partnerEatery?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  customerName: string;
  /**
   * e.g. "Baba Baidyanath Darshan, Mar 2026"
   */
  tripLabel?: string | null;
  tripType?: ('spiritual' | 'adventure' | 'wildlife' | 'beach' | 'cultural') | null;
  photos?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  quote: string;
  rating?: number | null;
  date?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name?: string | null;
  phone?: string | null;
  subjectType: 'package' | 'car' | 'hotel' | 'experience' | 'custom';
  /**
   * Package title / car / hotel referenced by the enquiry
   */
  subjectRef?: string | null;
  message?: string | null;
  travelers?: number | null;
  dates?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'fleet';
        value: number | Fleet;
      } | null)
    | ({
        relationTo: 'stays';
        value: number | Stay;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  featured?: T;
  category?: T;
  suitedFor?: T;
  region?: T;
  durationDays?: T;
  durationNights?: T;
  priceFrom?: T;
  compareAtPrice?: T;
  priceNote?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortPitch?: T;
  description?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        details?: T;
        id?: T;
      };
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet_select".
 */
export interface FleetSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  seats?: T;
  luggage?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  photo?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  rate?: T;
  compareAtRate?: T;
  rateNote?: T;
  ownedByKartikart?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays_select".
 */
export interface StaysSelect<T extends boolean = true> {
  name?: T;
  ownership?: T;
  location?: T;
  starRating?: T;
  amenities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDesc?: T;
  mapUrl?: T;
  description?: T;
  priceFrom?: T;
  priceNote?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  location?: T;
  specialty?: T;
  blurb?: T;
  mapUrl?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  partnerEatery?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  customerName?: T;
  tripLabel?: T;
  tripType?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  quote?: T;
  rating?: T;
  date?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  subjectType?: T;
  subjectRef?: T;
  message?: T;
  travelers?: T;
  dates?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, hero copy and social links used across the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandTagline?: string | null;
  heroHeadline?: string | null;
  heroSubline?: string | null;
  heroImages?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  /**
   * Digits only, with country code (used for wa.me booking links).
   */
  whatsappNumber: string;
  email?: string | null;
  instagram?: string | null;
  address?: string | null;
  /**
   * Google Maps embed URL.
   */
  mapEmbedUrl?: string | null;
  whatsappDefaultMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandTagline?: T;
  heroHeadline?: T;
  heroSubline?: T;
  heroImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  instagram?: T;
  address?: T;
  mapEmbedUrl?: T;
  whatsappDefaultMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}